import janus_swi as janus

# janus.query_once("abolish(neighborOf/2).")
# janus.query_once("abolish(locatedInCR/2).")
# janus.query_once("abolish_all_tables.")
janus.consult("without.pl")
# # # # janus.query_once("listing(locatedInCR/2).")
# # res = janus.query_once("locatedInCR(sint_maarten,americas).")
# # print(res)
# # # # res = janus.query_once("current_table(locatedInCR/2, X).")
# # # # print(res)
res = janus.query_once("locatedInCR(saint_martin,americas).")
print(res)
# # # res = janus.query_once("current_table(locatedInCR/2, X).")
# # # print(res)
# # # janus.query_once("halt.")
janus.query_once("abolish(neighborOf/2).")
janus.query_once("abolish(locatedInCR/2).")
janus.query_once("abolish_all_tables.")
# #
janus.consult("with.pl")
# # # janus.query_once("listing(locatedInCR/2).")
# # # res = janus.query_once("current_table(locatedInCR/2, X).")
# # # print(res)
# # res = janus.query_once("trace,locatedInCR(sint_maarten,americas).")
# # print(res)
res = janus.query_once("locatedInCR(sint_maarten,americas).")
print(res)
# # for d in res:
# #     print(d)

# janus.consult("without.pl")
# res = janus.query_once("locatedInCR(sint_maarten,americas).")
# print(res)
# # # # res = janus.query_once("current_table(locatedInCR/2, X).")
# # # # print(res)
# res = janus.query_once("locatedInCR(saint_martin,americas).")
# print(res)
# janus.consult("with.pl")
# #janus.query("assert(locatedInCR(sint_maarten,americas)).")
# res = janus.query_once("locatedInCR(sint_maarten,americas).")
# print(res)